apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: simplest #will become simplest-collector.svc.menarini.local
  namespace: menarini
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      debug: {}
      prometheus:

    service:
      extensions: [zpages]
      pipelines:
        metrics:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ debug ]
        traces:
          receivers: [ otlp ]
          processors: [ memory_limiter, batch ]
          exporters: [ debug ]
    extensions:
      zpages:
        endpoint: "0.0.0.0:55679"