spec:
  template:
    spec:
      containers:
        - env:
          - name: "SPRING_PROFILES_ACTIVE"
            value: "dev"
          - name: "OTEL_EXPORTER_OTLP_ENDPOINT"
            value: "http://simplest-collector.menarini.svc.cluster.local:4318"
          resources:
            requests:
              cpu: "1000m"
              memory: "1024Mi"
            limits:
              cpu: "1000m"
              memory: "2048Mi"
          readinessProbe:
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 60
            httpGet:
              port: 8080
              scheme: HTTP
              path: /actuator/health
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 120
            httpGet:
              port: 8080
              scheme: HTTP
              path: /actuator/health