spec:
  template:
    spec:
      containers:
        - name: springboot-demo
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "2048Mi"
          readinessProbe:
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 300
            httpGet:
              port: 8080
              scheme: HTTP
              path: /actuator/health
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 300
            httpGet:
              port: 8080
              scheme: HTTP
              path: /actuator/health