spec:
  template:
    spec:
      containers:
        - name: springboot-demo
          env:
          - name: "SPRING_PROFILES_ACTIVE"
            value: "prod"
          - name: "MANAGEMENT_OTLP_METRICS_EXPORT_URL"
            value: "http://simplest-collector.menarini.svc.cluster.local:4318/v1/metrics"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "2048Mi"
          readinessProbe:
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 300
            httpGet:
              port: 8080
              scheme: HTTP
              path: /actuator/health
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 300
            httpGet:
              port: 8080
              scheme: HTTP
              path: /actuator/health