apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${project.artifactId}
spec:
  scaleTargetRef:
    kind: Deployment
    name: ${project.artifactId}
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 90