management.endpoints.enabled-by-default = false

management.endpoint.health.enabled = true
management.endpoint.loggers.enabled = true
management.endpoint.env.enabled = true
management.endpoint.shutdown.enabled= true
management.endpoint.metrics.enabled= true
management.endpoint.threaddump.enabled=true
management.endpoint.heapdump.enabled=true
management.endpoint.info.enabled=true
management.endpoint.prometheus.enabled=true

management.endpoints.web.exposure.include=prometheus,true,metrics,health,shutdown,threaddump,heapdump

management.endpoint.health.show-details=always

management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.otlp.metrics.export.step=5s
management.opentelemetry.resource-attributes."service-name"=${spring.application.name}

logging.level.root=INFO
logging.level.com.vorozco=TRACE
spring.main.banner-mode=off