
spring.application.name="springboot-demo"

#management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
#management.otlp.metrics.export.step=5s
#management.opentelemetry.resource-attributes."service-name"=${spring.application.name}

#management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
#management.otlp.tracing.timeout=10s
#management.tracing.sampling.probability=1

logging.level.root=INFO
logging.level.com.vorozco=TRACE
spring.main.banner-mode=off

#Configurar los exporters
otel.logs.exporter=none
otel.metrics.exporter=otlp
otel.traces.exporter=otlp

#Configurar la generacion de datos
otel.metric.export.interval=5000
otel.instrumentation.micrometer.enabled=true

