spec:
  template:
    spec:
      containers:
        - env:
          - name: "MANAGEMENT_OTLP_TRACING_ENDPOINT"
            value: "http://simplest-collector.menarini.svc.cluster.local:4318/v1/traces"
          - name: "MANAGEMENT_OTLP_METRICS_EXPORT_URL"
            value: "http://simplest-collector.menarini.svc.cluster.local:4318/v1/metrics"
          - name: "SPRING_CLOUD_OPENFEIGN_CLIENT_CONFIG_BOOKS_URL"
            value: "http://springboot-demo.menarini.svc.cluster.local:8080"
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "2048Mi"
          readinessProbe:
            failureThreshold: 2
            successThreshold: 1
            initialDelaySeconds: 60
            httpGet:
              port: 8080
              scheme: HTTP
              path: /actuator/health
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 60
            httpGet:
              port: 8080
              scheme: HTTP
              path: /actuator/health