apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: es-flow
  namespace: menarini
spec:
  filters:
    - tag_normaliser: {}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: nginx
  match:
     - select:
         labels:
           app.kubernetes.io/name: log-generator
  localOutputRefs:
    - es-output