apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: menarini
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "infinity"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
