apiVersion: v1
kind: Secret
metadata:
  name: quickstart-es-elastic-user
  namespace: menarini
  labels:
    common.k8s.elastic.co/type: elasticsearch
    eck.k8s.elastic.co/credentials: 'true'
    eck.k8s.elastic.co/owner-kind: Elasticsearch
    eck.k8s.elastic.co/owner-name: quickstart
    eck.k8s.elastic.co/owner-namespace: elastic-system
    elasticsearch.k8s.elastic.co/cluster-name: quickstart
data:
  elastic: eTVUNFg0Mjk0RDVjMEk2YkRZUnhDZk4z
type: Opaque
